# Generated by Django 4.2 on 2023-04-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Neme product', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('Product', 'Продукт'), ('Service', 'Послуга')], max_length=10)),
                ('starting_quantity', models.IntegerField(help_text='кількість продуктів на складі до транзакції')),
                ('ending_quantity', models.IntegerField(help_text='кількість продуктів на складі після транзакції')),
                ('transaction_value', models.IntegerField(verbose_name='вартість всіх продуктів у транзакції')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Neme product', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('Product', 'Продукт'), ('Service', 'Послуга')], max_length=10)),
                ('starting_quantity', models.IntegerField(help_text='кількість продуктів на складі до транзакції')),
                ('ending_quantity', models.IntegerField(help_text='кількість продуктів на складі після транзакції')),
                ('transaction_value', models.IntegerField(verbose_name='вартість всіх продуктів у транзакції')),
            ],
        ),
    ]
